name: develop
on:
  push:
    branches:
      - develop
      - fix/*
      - feat/*
jobs:
  build:
    name: Install, check, build and test
    runs-on: ubuntu-latest
    environment: dev-api-donation.me-net.or.jp
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: donation
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, bcmath
          coverage: none

      - name: Copy .env
        run: cp .env.github_actions .env

      - name: Install
        run: make install
        env:
          # CI上では husky を動かさないようにする
          HUSKY: 0

      - name: Build
        run: bun run build

      - name: Migrate Database
        run: php artisan migrate:fresh --force
        env:
          DB_HOST: 127.0.0.1

      - name: Test
        run: php artisan test
        env:
          DB_HOST: 127.0.0.1
