name: production
on:
  push:
    branches: main
jobs:
  build:
    name: Install, check, build and deploy to Xserver
    runs-on: ubuntu-latest
    environment: api-donation.me-net.or.jp
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: donation
          MYSQL_USER: root
          MYSQL_PASSWOR: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          # XServerのNodeJSの最新バージョンは16.20.2
          node-version: 16.20.2
          cache: "npm"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, bcmath
          coverage: none

      - name: Install
        run: make install
        env:
          # CI上では husky を動かさないようにする
          HUSKY: 0

      - name: Build
        run: npm run build

      - name: Migrate Database
        run: php artisan migrate:fresh --force
        env:
          DB_HOST: 127.0.0.1

      - name: Test
        run: make test
        env:
          DB_HOST: 127.0.0.1

      - name: Deploy exported folder to Xserver through FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: laravel-project/api-donation.me-net.or.jp/
          local-dir: ./
          exclude: |
            .git*
            .git*/**
            .vscode/**
            node_modules/**
            vendor/**

      - name: Install and clear cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSWORD }}
          script: |
            cd laravel-project/api-donation.me-net.or.jp/
            cp .env.production .env
            make install
            make update
            make clear
